import { EntityTypeGenerationConfig, EntityTypeGenerationConfigSource } from '@/types';
import { describe, expect, it } from 'bun:test';
import createLiquibaseChangeset, { disambiguateSource } from './changeset';

describe('createLiquibaseChangeset', () => {
  it('generates a valid Liquibase changeset for a table', () => {
    const source: EntityTypeGenerationConfigSource = {
      name: 'test_view',
      table: 'test_table',
    };

    const config = {
      metadata: {
        module: 'mod-test',
        team: 'test-team',
        domain: 'erm',
      },
    } as EntityTypeGenerationConfig;

    const result = createLiquibaseChangeset(source, config);

    expect(result).toEqual({
      databaseChangeLog: [
        {
          changeSet: {
            id: 'create_view__test_view',
            author: 'generated--test-team--mod-test',
            runAlways: true,
            preConditions: [
              {
                onFail: 'CONTINUE',
              },
              {
                tableExists: {
                  tableName: 'test_table',
                  schemaName: '${tenant_id}_mod_test',
                },
              },
            ],
            changes: [
              {
                createView: {
                  replaceIfExists: true,
                  viewName: 'test_view',
                  selectQuery: 'SELECT * FROM ${tenant_id}_mod_test.test_table',
                  remarks: expect.stringContaining('Generated by fqm-tools for mod-test (test-team)'),
                },
              },
            ],
          },
        },
      ],
    });
  });
  it('generates a valid Liquibase changeset for a custom sql view', () => {
    const source: EntityTypeGenerationConfigSource = {
      name: 'test_view',
      sql: 'select 1=1',
    };

    const config = {
      metadata: {
        module: 'mod-test',
        team: 'test-team',
        domain: 'erm',
      },
    } as EntityTypeGenerationConfig;

    const result = createLiquibaseChangeset(source, config);

    expect(result).toEqual({
      databaseChangeLog: [
        {
          changeSet: {
            id: 'create_view__test_view',
            author: 'generated--test-team--mod-test',
            runAlways: true,
            preConditions: [
              {
                onFail: 'CONTINUE',
              },
            ],
            changes: [
              {
                createView: {
                  replaceIfExists: true,
                  viewName: 'test_view',
                  selectQuery: 'select 1=1',
                  remarks: expect.stringContaining('Generated by fqm-tools for mod-test (test-team)'),
                },
              },
            ],
          },
        },
      ],
    });
  });
});

describe('disambiguateSource', () => {
  it('disambiguates source name with metadata/table name', () => {
    const source: EntityTypeGenerationConfigSource = {
      name: 'test_view',
      table: 'test_table',
    };

    const config = {
      metadata: {
        module: 'mod-test-storage',
        team: 'test-team',
        domain: 'erm',
      },
    } as EntityTypeGenerationConfig;

    const result = disambiguateSource(source, config);

    expect(result).toEqual({
      name: 'src__erm__test_storage__test_table',
      table: 'test_table',
    });
  });

  it('disambiguates source name with source name', () => {
    const source: EntityTypeGenerationConfigSource = {
      name: 'cool_view',
      sql: 'select 1=1',
    };

    const config = {
      metadata: {
        module: 'mod-test-storage',
        team: 'test-team',
        domain: 'erm',
      },
    } as EntityTypeGenerationConfig;

    const result = disambiguateSource(source, config);

    expect(result).toEqual({
      name: 'src__erm__test_storage__cool_view',
      sql: 'select 1=1',
    });
  });
});
