name: Lint

on:
  # linting already happens in build.yaml, however, running it like this adds annotations to the
  #   PR's file tab inline with the code
  - pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2

      - run: bun install --frozen-lockfile

      - run: bun run lint --output-file eslint_report.json --format json
        continue-on-error: true

      - uses: ataylorme/eslint-annotate-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          fail-on-warning: true
          report-json: eslint_report.json
