name: Scheduled entity type generation

on:
  # push: {} # for manual testing
  schedule:
    - cron: '0 */3 * * *'

jobs:
  scheduled-generate:
    uses: ./.github/workflows/generate-entity-types.yaml
    secrets: inherit
    with:
      create-pr: 'yes'
      send-slack: true
