name: Test PR creation

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Clone repositories
        run: bun scripts/entity-generation/1-clone-repositories.ts
        env:
          DEBUG: '*'

      - name: Run generation
        run: bun scripts/entity-generation/2-run-generation.ts | tee generation.log
        env:
          DEBUG: '*'

      - name: Login as PR-creating app
        uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: folio-org
          repositories: mod-fqm-manager

      - name: Checkout mod-fqm-manager
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: folio-org/mod-fqm-manager
          token: ${{ steps.generate-token.outputs.token }}
          path: mod-fqm-manager

      - name: Generate report
        run: bun scripts/entity-generation/3-generate-report.ts --base-dir mod-fqm-manager --generated-dir out --error-log generation.log | tee report.md

      - name: Stage changes
        run: bun scripts/entity-generation/4-stage-changes.ts --base-dir mod-fqm-manager --generated-dir out --error-log generation.log

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        id: create-pr
        with:
          token: ${{ steps.generate-token.outputs.token }}
          sign-commits: true
          branch: autogenerated-staging
          labels: ✨autogenerated✨
          body-path: report.md

      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto --repo folio-org/mod-fqm-manager "${{ steps.create-pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Upload generated files
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: generated-result
          path: out

      - name: Upload issue log
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: issues
          path: generation.log
