name: Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2

      - run: bun install --frozen-lockfile

      - run: bun test --coverage --reporter=junit --reporter-outfile=./test-results.xml

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@3a74b2957438d0b6e2e61d67b05318aa25c9e6c6 # v2
        if: ${{ !cancelled() }}
        with:
          check_name: Unit Test Results
          files: './test-results.xml'

      - name: Run Sonar scan
        uses: sonarsource/sonarqube-scan-action@2500896589ef8f7247069a56136f8dc177c27ccf # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=folio-org
            -Dsonar.projectKey=org.folio:fqm-tools
            -Dsonar.projectName=fqm-tools
            -Dsonar.sources=src
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.exclusions=**/*.md,LICENSE,artifacts/**,ci/**,node_modules/**,**/tests/**,**/test/**,**/*-test.*,**/*.test.*,karma.conf.*,jest.config.*,**/*.css,**/*.json
