name: Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2

      - run: bun install --frozen-lockfile

      - run: bun test --coverage --reporter=junit --reporter-outfile=./test-results.xml

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2
        if: ${{ !cancelled() }}
        with:
          check_name: Unit Test Results
          files: './test-results.xml'

      - name: Run Sonar scan
        uses: sonarsource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=folio-org
            -Dsonar.projectKey=org.folio:fqm-tools
            -Dsonar.projectName=fqm-tools
            -Dsonar.sources=src
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.exclusions=**/*.md,LICENSE,artifacts/**,ci/**,node_modules/**,**/tests/**,**/test/**,**/*-test.*,**/*.test.*,karma.conf.*,jest.config.*,**/*.css,**/*.json
